CREATE
TYPE CURRENCY AS ENUM ('PLN', 'EUR', 'USD');


ALTER TABLE ACCOUNTS
    ADD COLUMN CURRENCY CURRENCY NOT NULL;


CREATE TABLE IF NOT EXISTS TRANSFERS
(
    ID BIGSERIAL PRIMARY KEY,
    SOURCE_ID      BIGINT REFERENCES ACCOUNTS (ID) NOT NULL,
    DESTINATION_ID BIGINT REFERENCES ACCOUNTS (ID) NOT NULL,
    AMOUNT         DECIMAL(20, 3)                  NOT NULL,
    CURRENCY CURRENCY NOT NULL,
    TITLE          TEXT                            NOT NULL
);